version: "3.6"

services:
 db:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    volumes:
      - db_new:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

 web:
    container_name: web
    build:
      context: .
      dockerfile: _prod/Dockerfile
    command: gunicorn ${APP_NAME}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - _static:/code/_static
      - _media:/code/_media
    expose:
      - 8000
    depends_on:
      - db

 nginx:
   container_name: nginx
   build: _prod/nginx
   ports:
     - ${NGINX_EXPOSE}:80
   depends_on:
     - web
   volumes:
     - _static:/code/_static
     - _media:/code/_media


volumes:
  db_new:
  _static:
  _media: